name: Deploy Github Pages
inputs:
  path:
    description: The path to deploy
    required: true
runs:
  using: composite
  steps:
    - name: Setup Pages
      uses: actions/configure-pages@v6
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v5.0.0
      with:
        path: ${{ inputs.path }}
        name: github-pages-${{ github.run_attempt }}
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v5
      with:
        artifact_name: github-pages-${{ github.run_attempt }}
